CREATE TABLE [dbo].[DI_DRIVER_AUDIT_TABLE](
ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
ControlTableId int,
DataFactoryName nvarchar(max),
EffectiveIntegrationRuntime nvarchar(max),
QueuingDurationInSecs nvarchar(max),
StartTime nvarchar(max),
EndTime nvarchar(max),
CopyDurationInSecs nvarchar(max),
NoParallelCopies nvarchar(max),
ExecutionStatus nvarchar(max),
ErrorCode nvarchar(max),
StoredProcExecutionStatus nvarchar(max),
pipeline_name nvarchar(max),
process_name nvarchar(max),
interface_name nvarchar(max),
ErrorMessage nvarchar(max),
FullErrorMessage nvarchar(max),
Layer nvarchar(max),
TargetTable nvarchar(max),
SourceTable nvarchar(max),
TargetTableCount nvarchar(max),
SourceTableCount nvarchar(max),
Env nvarchar(max),
NotebookLocation nvarchar(max),
DatabricksJobId nvarchar(max),
DatabricksRunId nvarchar(max),
adfRunId nvarchar(max),
adfJobId nvarchar(max),
details nvarchar(max)
);