name: Master Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: choice
        options:
          - dev
          - qat
          - prod
        required: true
      function_name:
        description: 'Select Data Source to deploy'
        type: choice
        options:
          - none
          - all
          - IQVIA_SALES
          - SA_INSIGHTS
          - MPB-MNC
          - SFDC_CRM
          - VARICENT_SALES
        required: true
      databricks_deployment:
        description: 'Enable Databricks Deployment?'
        type: boolean
        required: true
      databricks_deployment_steps:
        description: 'Select Databricks deployment step'
        type: choice
        options:
          - none
          - ingestion_utilities
          - ddl
          - dml
          - all
        required: false
        default: 'none'
      deploy_linked_service:
        description: 'Deploy ADF Linked Services'
        type: boolean
        required: false
      deploy_datasets:
        description: 'Deploy ADF Datasets'
        type: boolean
        required: false
      deploy_common_pipelines:
        description: 'Deploy ADF Common Pipelines'
        type: boolean
        required: false
      deploy_triggers:
        description: 'Deploy ADF Triggers'
        type: boolean
        required: false
      date:
        description: 'Deploy changes after a commit date in YYYY-MM-DD format (OPTIONAL)'
        type: string
        default: '1999-01-01'
        required: true

env:
  ENVIRONMENT: ${{ inputs.environment }}
  DATE: ${{ inputs.date }}

jobs:
  validate_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Date Format
        run: |
          if ! [[ "${{ inputs.date }}" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            echo "Invalid date format. Please use YYYY-MM-DD."
            exit 1
          fi
          
      - name: Validate Future Date
        run: |
          if [[ "${{ inputs.date }}" > "$(date +%Y-%m-%d)" ]]; then
            echo "The specified date is in the future. Please provide a valid past date."
            exit 1
          fi
          
      - name: Validate Environment Selection
        run: |
          if [[ -z "${{ inputs.environment }}" ]]; then
            echo "Environment selection cannot be empty."
            exit 1
          fi
          
      - name: Validate Function Name
        run: |
          if [[ "${{ inputs.function_name }}" == "none" && ( "${{ inputs.databricks_deployment }}" == "true" || "${{ inputs.deploy_datasets }}" == "true" || "${{ inputs.deploy_linked_service }}" == "true" || "${{ inputs.deploy_common_pipelines }}" == "true" || "${{ inputs.deploy_triggers }}" == "true" ) ]]; then
            echo "If 'function_name' is 'none', no deployment options should be selected."
            exit 1
          fi
          
      - name: Validate Databricks Deployment Steps
        run: |
          if [[ "${{ inputs.databricks_deployment }}" == "true" && "${{ inputs.databricks_deployment_steps }}" == "none" ]]; then
            echo "If Databricks deployment is enabled, at least one deployment step must be selected."
            exit 1
          fi
          
      - name: Validate Linked Services and Datasets Deployment
        run: |
          if [[ "${{ inputs.deploy_linked_service }}" == "true" || "${{ inputs.deploy_datasets }}" == "true" ]]; then
            if [[ "${{ inputs.function_name }}" == "none" ]]; then
              echo "If deploying linked services or datasets, a valid function name must be provided."
              exit 1
            fi
          fi

  trigger_workflows:
    name: Trigger Deployment Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Trigger Databricks Deployment
      - name: Trigger Databricks Deployment
        if: ${{ inputs.databricks_deployment == true }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/main", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}", "databricks_deployment_steps": "${{ inputs.databricks_deployment_steps }}", "function_name": "${{ inputs.function_name }}"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/databricks.yml/dispatches

      # Trigger ADF Datasets Deployment
      - name: Trigger ADF Datasets Deployment
        if: ${{ inputs.deploy_datasets == true }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/main", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_dataset.yml/dispatches

      # Trigger ADF Linked Services Deployment
      - name: Trigger ADF Linked Services Deployment
        if: ${{ inputs.deploy_linked_service == true }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/main", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_linked_service.yml/dispatches

      # Trigger ADF Common Pipelines Deployment
      - name: Trigger ADF Common Pipelines Deployment
        if: ${{ inputs.deploy_common_pipelines == true }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/main", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_common_pipelines.yml/dispatches

      # Trigger ADF Triggers Deployment
      - name: Trigger ADF Triggers Deployment
        if: ${{ inputs.deploy_triggers == true }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/main", "inputs": {"environment": "${{ inputs.environment }}", "date": "${{ inputs.date }}"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_triggers.yml/dispatches
